<?php

namespace Container1viGJZp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_G1qvMh8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.G1qvMh8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'commandeRepository' => ['privates', 'App\\Repository\\CommandeRepository', 'getCommandeRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'commandeRepository' => 'App\\Repository\\CommandeRepository',
            'paginator' => '?',
        ]);

        if (isset($container->privates['.service_locator.G1qvMh8'])) {
            return $container->privates['.service_locator.G1qvMh8'];
        }

        return $container->privates['.service_locator.G1qvMh8'] = $instance;
    }
}
