<?php

namespace Container1viGJZp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PRAmgeoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pRAmgeo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categorieRepository' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'produitRepository' => ['privates', 'App\\Repository\\ProduitRepository', 'getProduitRepositoryService', true],
        ], [
            'categorieRepository' => 'App\\Repository\\CategorieRepository',
            'paginator' => '?',
            'produitRepository' => 'App\\Repository\\ProduitRepository',
        ]);

        if (isset($container->privates['.service_locator.pRAmgeo'])) {
            return $container->privates['.service_locator.pRAmgeo'];
        }

        return $container->privates['.service_locator.pRAmgeo'] = $instance;
    }
}
