<?php

namespace Container1viGJZp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_P4_6uh0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.P4.6uh0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'emailService' => ['privates', 'App\\Service\\EmailService', 'getEmailServiceService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'panierRepository' => ['privates', 'App\\Repository\\PanierRepository', 'getPanierRepositoryService', true],
        ], [
            'emailService' => 'App\\Service\\EmailService',
            'entityManager' => '?',
            'panierRepository' => 'App\\Repository\\PanierRepository',
        ]);

        if (isset($container->privates['.service_locator.P4.6uh0'])) {
            return $container->privates['.service_locator.P4.6uh0'];
        }

        return $container->privates['.service_locator.P4.6uh0'] = $instance;
    }
}
