<?php

namespace Container1viGJZp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPdfTicketServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\PdfTicketService' shared autowired service.
     *
     * @return \App\Service\PdfTicketService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'PdfTicketService.php';

        $a = ($container->privates['twig'] ?? self::getTwigService($container));

        if (isset($container->privates['App\\Service\\PdfTicketService'])) {
            return $container->privates['App\\Service\\PdfTicketService'];
        }

        $instance = new \App\Service\PdfTicketService(($container->services['Knp\\Snappy\\Pdf'] ?? $container->load('getPdfService')), $a);

        if (isset($container->privates['App\\Service\\PdfTicketService'])) {
            return $container->privates['App\\Service\\PdfTicketService'];
        }

        return $container->privates['App\\Service\\PdfTicketService'] = $instance;
    }
}
