vich_uploader:
    db_driver: orm
    mappings:
        forum_images:
            uri_prefix: /uploads/forum
            upload_destination: '%kernel.project_dir%/public/uploads/forum'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
