
services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      - database
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: ${MYSQL_USER:-app}
      PMA_PASSWORD: ${MYSQL_PASSWORD:-!ChangeMe!}
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###
