<?php

namespace ContainerGNUVICY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_J0UfbYAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.J0UfbYA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.J0UfbYA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'artRepository' => ['privates', 'App\\Repository\\ArtRepository', 'getArtRepositoryService', true],
        ], [
            'artRepository' => 'App\\Repository\\ArtRepository',
        ]);
    }
}
