<?php

namespace ContainerGNUVICY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FQAHiFNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FQAHiFN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'artRepository' => ['privates', 'App\\Repository\\ArtRepository', 'getArtRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'artRepository' => 'App\\Repository\\ArtRepository',
            'entityManager' => '?',
        ]);

        if (isset($container->privates['.service_locator.FQAHiFN'])) {
            return $container->privates['.service_locator.FQAHiFN'];
        }

        return $container->privates['.service_locator.FQAHiFN'] = $instance;
    }
}
