<?php

namespace ContainerGNUVICY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WrrH9GsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wrrH9Gs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\ArtArchiveController::archive' => ['privates', '.service_locator.FQAHiFN', 'get_ServiceLocator_FQAHiFNService', true],
            'App\\Controller\\ArtArchiveController::delete' => ['privates', '.service_locator.FQAHiFN', 'get_ServiceLocator_FQAHiFNService', true],
            'App\\Controller\\ArtArchiveController::getArchivedArts' => ['privates', '.service_locator.J0UfbYA', 'get_ServiceLocator_J0UfbYAService', true],
            'App\\Controller\\ArtArchiveController::restore' => ['privates', '.service_locator.FQAHiFN', 'get_ServiceLocator_FQAHiFNService', true],
            'App\\Controller\\ArtArchiveController::updateStatus' => ['privates', '.service_locator.FQAHiFN', 'get_ServiceLocator_FQAHiFNService', true],
            'App\\Controller\\BackController::artArchives' => ['privates', '.service_locator.J0UfbYA', 'get_ServiceLocator_J0UfbYAService', true],
            'App\\Controller\\BackController::artList' => ['privates', '.service_locator.J0UfbYA', 'get_ServiceLocator_J0UfbYAService', true],
            'App\\Controller\\BackController::dashboard' => ['privates', '.service_locator.J0UfbYA', 'get_ServiceLocator_J0UfbYAService', true],
            'App\\Controller\\BackController::delete' => ['privates', '.service_locator.FQAHiFN', 'get_ServiceLocator_FQAHiFNService', true],
            'App\\Controller\\BackController::edit' => ['privates', '.service_locator.FQAHiFN', 'get_ServiceLocator_FQAHiFNService', true],
            'App\\Controller\\BackController::page' => ['privates', '.service_locator.J0UfbYA', 'get_ServiceLocator_J0UfbYAService', true],
            'App\\Controller\\BackController::updateStatus' => ['privates', '.service_locator.FQAHiFN', 'get_ServiceLocator_FQAHiFNService', true],
            'App\\Controller\\GalleryController::delete' => ['privates', '.service_locator..eBmjmm', 'get_ServiceLocator__EBmjmmService', true],
            'App\\Controller\\GalleryController::edit' => ['privates', '.service_locator..eBmjmm', 'get_ServiceLocator__EBmjmmService', true],
            'App\\Controller\\GalleryController::index' => ['privates', '.service_locator.J0UfbYA', 'get_ServiceLocator_J0UfbYAService', true],
            'App\\Controller\\GalleryController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\LikeController::toggleLike' => ['privates', '.service_locator.dufBNWY', 'get_ServiceLocator_DufBNWYService', true],
            'App\\Controller\\StatsController::getStats' => ['privates', '.service_locator.J0UfbYA', 'get_ServiceLocator_J0UfbYAService', true],
            'App\\Controller\\TranslateController::translate' => ['privates', '.service_locator.xiXknQG', 'get_ServiceLocator_XiXknQGService', true],
            'App\\Controller\\ViewController::addView' => ['privates', '.service_locator.oq3eYY.', 'get_ServiceLocator_Oq3eYY_Service', true],
            'App\\Controller\\ViewController::getViewsCount' => ['privates', '.service_locator.E2FvEcj', 'get_ServiceLocator_E2FvEcjService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\ArtArchiveController:archive' => ['privates', '.service_locator.FQAHiFN', 'get_ServiceLocator_FQAHiFNService', true],
            'App\\Controller\\ArtArchiveController:delete' => ['privates', '.service_locator.FQAHiFN', 'get_ServiceLocator_FQAHiFNService', true],
            'App\\Controller\\ArtArchiveController:getArchivedArts' => ['privates', '.service_locator.J0UfbYA', 'get_ServiceLocator_J0UfbYAService', true],
            'App\\Controller\\ArtArchiveController:restore' => ['privates', '.service_locator.FQAHiFN', 'get_ServiceLocator_FQAHiFNService', true],
            'App\\Controller\\ArtArchiveController:updateStatus' => ['privates', '.service_locator.FQAHiFN', 'get_ServiceLocator_FQAHiFNService', true],
            'App\\Controller\\BackController:artArchives' => ['privates', '.service_locator.J0UfbYA', 'get_ServiceLocator_J0UfbYAService', true],
            'App\\Controller\\BackController:artList' => ['privates', '.service_locator.J0UfbYA', 'get_ServiceLocator_J0UfbYAService', true],
            'App\\Controller\\BackController:dashboard' => ['privates', '.service_locator.J0UfbYA', 'get_ServiceLocator_J0UfbYAService', true],
            'App\\Controller\\BackController:delete' => ['privates', '.service_locator.FQAHiFN', 'get_ServiceLocator_FQAHiFNService', true],
            'App\\Controller\\BackController:edit' => ['privates', '.service_locator.FQAHiFN', 'get_ServiceLocator_FQAHiFNService', true],
            'App\\Controller\\BackController:page' => ['privates', '.service_locator.J0UfbYA', 'get_ServiceLocator_J0UfbYAService', true],
            'App\\Controller\\BackController:updateStatus' => ['privates', '.service_locator.FQAHiFN', 'get_ServiceLocator_FQAHiFNService', true],
            'App\\Controller\\GalleryController:delete' => ['privates', '.service_locator..eBmjmm', 'get_ServiceLocator__EBmjmmService', true],
            'App\\Controller\\GalleryController:edit' => ['privates', '.service_locator..eBmjmm', 'get_ServiceLocator__EBmjmmService', true],
            'App\\Controller\\GalleryController:index' => ['privates', '.service_locator.J0UfbYA', 'get_ServiceLocator_J0UfbYAService', true],
            'App\\Controller\\GalleryController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\LikeController:toggleLike' => ['privates', '.service_locator.dufBNWY', 'get_ServiceLocator_DufBNWYService', true],
            'App\\Controller\\StatsController:getStats' => ['privates', '.service_locator.J0UfbYA', 'get_ServiceLocator_J0UfbYAService', true],
            'App\\Controller\\TranslateController:translate' => ['privates', '.service_locator.xiXknQG', 'get_ServiceLocator_XiXknQGService', true],
            'App\\Controller\\ViewController:addView' => ['privates', '.service_locator.oq3eYY.', 'get_ServiceLocator_Oq3eYY_Service', true],
            'App\\Controller\\ViewController:getViewsCount' => ['privates', '.service_locator.E2FvEcj', 'get_ServiceLocator_E2FvEcjService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\ArtArchiveController::archive' => '?',
            'App\\Controller\\ArtArchiveController::delete' => '?',
            'App\\Controller\\ArtArchiveController::getArchivedArts' => '?',
            'App\\Controller\\ArtArchiveController::restore' => '?',
            'App\\Controller\\ArtArchiveController::updateStatus' => '?',
            'App\\Controller\\BackController::artArchives' => '?',
            'App\\Controller\\BackController::artList' => '?',
            'App\\Controller\\BackController::dashboard' => '?',
            'App\\Controller\\BackController::delete' => '?',
            'App\\Controller\\BackController::edit' => '?',
            'App\\Controller\\BackController::page' => '?',
            'App\\Controller\\BackController::updateStatus' => '?',
            'App\\Controller\\GalleryController::delete' => '?',
            'App\\Controller\\GalleryController::edit' => '?',
            'App\\Controller\\GalleryController::index' => '?',
            'App\\Controller\\GalleryController::new' => '?',
            'App\\Controller\\LikeController::toggleLike' => '?',
            'App\\Controller\\StatsController::getStats' => '?',
            'App\\Controller\\TranslateController::translate' => '?',
            'App\\Controller\\ViewController::addView' => '?',
            'App\\Controller\\ViewController::getViewsCount' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ArtArchiveController:archive' => '?',
            'App\\Controller\\ArtArchiveController:delete' => '?',
            'App\\Controller\\ArtArchiveController:getArchivedArts' => '?',
            'App\\Controller\\ArtArchiveController:restore' => '?',
            'App\\Controller\\ArtArchiveController:updateStatus' => '?',
            'App\\Controller\\BackController:artArchives' => '?',
            'App\\Controller\\BackController:artList' => '?',
            'App\\Controller\\BackController:dashboard' => '?',
            'App\\Controller\\BackController:delete' => '?',
            'App\\Controller\\BackController:edit' => '?',
            'App\\Controller\\BackController:page' => '?',
            'App\\Controller\\BackController:updateStatus' => '?',
            'App\\Controller\\GalleryController:delete' => '?',
            'App\\Controller\\GalleryController:edit' => '?',
            'App\\Controller\\GalleryController:index' => '?',
            'App\\Controller\\GalleryController:new' => '?',
            'App\\Controller\\LikeController:toggleLike' => '?',
            'App\\Controller\\StatsController:getStats' => '?',
            'App\\Controller\\TranslateController:translate' => '?',
            'App\\Controller\\ViewController:addView' => '?',
            'App\\Controller\\ViewController:getViewsCount' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);

        if (isset($container->privates['.service_locator.wrrH9Gs'])) {
            return $container->privates['.service_locator.wrrH9Gs'];
        }

        return $container->privates['.service_locator.wrrH9Gs'] = $instance;
    }
}
