<?php

namespace ContainerGNUVICY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Oq3eYY_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oq3eYY.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'art' => ['privates', '.errored..service_locator.oq3eYY..App\\Entity\\Art', NULL, 'Cannot autowire service ".service_locator.oq3eYY.": it needs an instance of "App\\Entity\\Art" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'viewRepository' => ['privates', 'App\\Repository\\ArtViewRepository', 'getArtViewRepositoryService', true],
        ], [
            'art' => 'App\\Entity\\Art',
            'entityManager' => '?',
            'viewRepository' => 'App\\Repository\\ArtViewRepository',
        ]);

        if (isset($container->privates['.service_locator.oq3eYY.'])) {
            return $container->privates['.service_locator.oq3eYY.'];
        }

        return $container->privates['.service_locator.oq3eYY.'] = $instance;
    }
}
