<?php

namespace ContainerGsrKFYt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_A3Ng9trService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.a3Ng9tr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.a3Ng9tr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'aiService' => ['privates', 'App\\Service\\AIService', 'getAIServiceService', true],
            'produitRepository' => ['privates', 'App\\Repository\\ProduitRepository', 'getProduitRepositoryService', true],
        ], [
            'aiService' => 'App\\Service\\AIService',
            'produitRepository' => 'App\\Repository\\ProduitRepository',
        ]);
    }
}
