<?php

namespace ContainerGsrKFYt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AnCioW9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.anCioW9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'commande' => ['privates', '.errored..service_locator.anCioW9.App\\Entity\\Commande', NULL, 'Cannot autowire service ".service_locator.anCioW9": it needs an instance of "App\\Entity\\Commande" but this type has been excluded in "config/services.yaml".'],
            'pdfTicketService' => ['privates', 'App\\Service\\PdfTicketService', 'getPdfTicketServiceService', true],
        ], [
            'commande' => 'App\\Entity\\Commande',
            'pdfTicketService' => 'App\\Service\\PdfTicketService',
        ]);

        if (isset($container->privates['.service_locator.anCioW9'])) {
            return $container->privates['.service_locator.anCioW9'];
        }

        return $container->privates['.service_locator.anCioW9'] = $instance;
    }
}
