<?php

namespace ContainerGsrKFYt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OP1QTkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oP1_qTk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'panierRepository' => ['privates', 'App\\Repository\\PanierRepository', 'getPanierRepositoryService', true],
            'produitRepository' => ['privates', 'App\\Repository\\ProduitRepository', 'getProduitRepositoryService', true],
        ], [
            'entityManager' => '?',
            'panierRepository' => 'App\\Repository\\PanierRepository',
            'produitRepository' => 'App\\Repository\\ProduitRepository',
        ]);

        if (isset($container->privates['.service_locator.oP1_qTk'])) {
            return $container->privates['.service_locator.oP1_qTk'];
        }

        return $container->privates['.service_locator.oP1_qTk'] = $instance;
    }
}
