<?php

namespace ContainerGsrKFYt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAIServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\AIService' shared autowired service.
     *
     * @return \App\Service\AIService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'AIService.php';

        return $container->privates['App\\Service\\AIService'] = new \App\Service\AIService(($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)), $container->getEnv('GEMINI_API_KEY'));
    }
}
