<?php

namespace ContainerO2NkSvW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_E2FvEcjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.E2FvEcj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.E2FvEcj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'art' => ['privates', '.errored..service_locator.E2FvEcj.App\\Entity\\Art', NULL, 'Cannot autowire service ".service_locator.E2FvEcj": it needs an instance of "App\\Entity\\Art" but this type has been excluded in "config/services.yaml".'],
            'viewRepository' => ['privates', 'App\\Repository\\ArtViewRepository', 'getArtViewRepositoryService', true],
        ], [
            'art' => 'App\\Entity\\Art',
            'viewRepository' => 'App\\Repository\\ArtViewRepository',
        ]);
    }
}
