<?php

namespace ContainerO2NkSvW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArt2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.E2FvEcj.App\Entity\Art' shared service.
     *
     * @return \App\Entity\Art
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.E2FvEcj": it needs an instance of "App\\Entity\\Art" but this type has been excluded in "config/services.yaml".');
    }
}
