<?php

namespace ContainerO2NkSvW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeeplTranslatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\DeeplTranslator' shared autowired service.
     *
     * @return \App\Service\DeeplTranslator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'DeeplTranslator.php';

        return $container->privates['App\\Service\\DeeplTranslator'] = new \App\Service\DeeplTranslator(($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)), $container->getEnv('DEEPL_API_KEY'), $container->getEnv('DEEPL_API_BASE_URL'));
    }
}
