<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerO2NkSvW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerO2NkSvW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerO2NkSvW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerO2NkSvW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerO2NkSvW\App_KernelDevDebugContainer([
    'container.build_hash' => 'O2NkSvW',
    'container.build_id' => 'abc7f578',
    'container.build_time' => 1771465480,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerO2NkSvW');
